function shallowStage(stageId, entries) {
  return entries.map(
    ([lessonRole, exerciseKind, title, text, input, preferredInput, learningTags], index) => ({
      id: `${stageId.toLowerCase()}-${String(index + 1).padStart(2, "0")}`,
      stageId,
      title,
      text,
      input,
      inputMode: "ja-romaji",
      preferredInput,
      targetKeys: [...new Set(preferredInput)],
      tags: ["kana", exerciseKind, ...learningTags],
      learningTags,
      lessonRole,
      exerciseKind,
      estimatedKeystrokes: preferredInput.length,
    }),
  );
}

const SH01 = shallowStage("SH01", [
  ["intro", "pattern", "A は「あ」", "あ", "あ", "a", ["vowel", "a-row"]],
  ["intro", "pattern", "I は「い」", "い", "い", "i", ["vowel", "a-row"]],
  ["intro", "pattern", "U は「う」", "う", "う", "u", ["vowel", "a-row"]],
  ["intro", "pattern", "E は「え」", "え", "え", "e", ["vowel", "a-row"]],
  ["practice", "pattern", "O は「お」", "お", "お", "o", ["vowel", "a-row"]],
  ["practice", "word", "ふたつの 音", "あい", "あい", "ai", ["vowel", "a-row"]],
  ["practice", "word", "帰る ばしょ", "いえ", "いえ", "ie", ["vowel", "a-row"]],
  ["practice", "word", "高い ところ", "うえ", "うえ", "ue", ["vowel", "a-row"]],
  ["practice", "word", "海の いろ", "あお", "あお", "ao", ["vowel", "a-row"]],
  ["practice", "pattern", "O から I", "おい", "おい", "oi", ["vowel", "a-row"]],
  ["mixed", "pattern", "三つを つなぐ", "あいう", "あいう", "aiu", ["vowel", "a-row"]],
  ["mixed", "pattern", "まんなかの 三つ", "いうえ", "いうえ", "iue", ["vowel", "a-row"]],
  ["mixed", "pattern", "後ろの 三つ", "うえお", "うえお", "ueo", ["vowel", "a-row"]],
  ["mixed", "pattern", "四つを つなぐ", "あいうえ", "あいうえ", "aiue", ["vowel", "a-row"]],
  ["treasure", "pattern", "I から O まで", "いうえお", "いうえお", "iueo", ["vowel", "a-row"]],
  ["treasure", "pattern", "母音の なみ", "あいうえお", "あいうえお", "aiueo", ["vowel", "a-row"]],
  ["treasure", "pattern", "帰りの なみ", "おえういあ", "おえういあ", "oeuia", ["vowel", "a-row"]],
  ["treasure", "pattern", "青い なみ", "あおいうえ", "あおいうえ", "aoiue", ["vowel", "a-row"]],
]);

const SH02 = shallowStage("SH02", [
  ["intro", "pattern", "K と A で「か」", "か", "か", "ka", ["consonant-vowel", "k-row"]],
  ["intro", "pattern", "K と I で「き」", "き", "き", "ki", ["consonant-vowel", "k-row"]],
  ["intro", "pattern", "K と U で「く」", "く", "く", "ku", ["consonant-vowel", "k-row"]],
  ["intro", "pattern", "K と E で「け」", "け", "け", "ke", ["consonant-vowel", "k-row"]],
  ["practice", "pattern", "K と O で「こ」", "こ", "こ", "ko", ["consonant-vowel", "k-row"]],
  ["practice", "pattern", "二つを つなぐ", "かき", "かき", "kaki", ["consonant-vowel", "k-row"]],
  ["practice", "pattern", "となりの 音", "くけ", "くけ", "kuke", ["consonant-vowel", "k-row"]],
  ["practice", "pattern", "ぐるりと まわる", "こか", "こか", "koka", ["consonant-vowel", "k-row"]],
  ["practice", "pattern", "母音を かえる", "かく", "かく", "kaku", ["consonant-vowel", "k-row"]],
  ["practice", "pattern", "I から O へ", "きこ", "きこ", "kiko", ["consonant-vowel", "k-row"]],
  ["practice", "pattern", "か行の なみ", "かきくけこ", "かきくけこ", "kakikukeko", ["consonant-vowel", "k-row"]],
  ["practice", "word", "にっこり えがお", "かお", "かお", "kao", ["consonant-vowel", "k-row"]],
  ["mixed", "word", "声を きこう", "こえ", "こえ", "koe", ["consonant-vowel", "k-row"]],
  ["mixed", "word", "水の ある ところ", "いけ", "いけ", "ike", ["consonant-vowel", "k-row"]],
  ["mixed", "word", "電車が とまる", "えき", "えき", "eki", ["consonant-vowel", "k-row"]],
  ["mixed", "word", "葉が いろづく", "あき", "あき", "aki", ["consonant-vowel", "k-row"]],
  ["treasure", "word", "海を およぐ", "いか", "いか", "ika", ["consonant-vowel", "k-row"]],
  ["treasure", "word", "浜辺で みつけた", "かい", "かい", "kai", ["consonant-vowel", "k-row"]],
  ["treasure", "word", "池の さかな", "こい", "こい", "koi", ["consonant-vowel", "k-row"]],
  ["treasure", "word", "花を ささえる", "くき", "くき", "kuki", ["consonant-vowel", "k-row"]],
]);

const SH03 = shallowStage("SH03", [
  ["intro", "pattern", "S を つけよう", "さしすせそ", "さしすせそ", "sashisuseso", ["s-row", "variant-shi"]],
  ["intro", "pattern", "T を つけよう", "たちつてと", "たちつてと", "tachitsuteto", ["t-row", "variant-chi", "variant-tsu"]],
  ["intro", "pattern", "SHI で「し」", "し", "し", "shi", ["s-row", "variant-shi"]],
  ["intro", "pattern", "CHI で「ち」", "ち", "ち", "chi", ["t-row", "variant-chi"]],
  ["practice", "pattern", "TSU で「つ」", "つ", "つ", "tsu", ["t-row", "variant-tsu"]],
  ["practice", "pattern", "S の 音を まぜる", "させそ", "させそ", "saseso", ["s-row"]],
  ["practice", "pattern", "T の 音を まぜる", "たてと", "たてと", "tateto", ["t-row"]],
  ["practice", "pattern", "三つの とくべつ", "しちつ", "しちつ", "shichitsu", ["s-row", "t-row", "variant-shi", "variant-chi", "variant-tsu"]],
  ["practice", "word", "朝の ひかり", "あさ", "あさ", "asa", ["s-row"]],
  ["practice", "word", "雨の おとも", "かさ", "かさ", "kasa", ["s-row", "k-row"]],
  ["practice", "word", "海の ごちそう", "すし", "すし", "sushi", ["s-row", "variant-shi"]],
  ["practice", "word", "すわる ばしょ", "せき", "せき", "seki", ["s-row", "k-row"]],
  ["practice", "word", "下の ほう", "そこ", "そこ", "soko", ["s-row", "k-row"]],
  ["practice", "word", "空を およぐ", "たこ", "たこ", "tako", ["t-row", "k-row"]],
  ["mixed", "word", "夜の ひかり", "つき", "つき", "tsuki", ["t-row", "k-row", "variant-tsu"]],
  ["mixed", "word", "時を しらせる", "とけい", "とけい", "tokei", ["t-row", "k-row"]],
  ["mixed", "word", "足に はく", "くつ", "くつ", "kutsu", ["k-row", "t-row", "variant-tsu"]],
  ["mixed", "word", "足の ほう", "した", "した", "shita", ["s-row", "t-row", "variant-shi"]],
  ["mixed", "word", "すぐ そば", "ちか", "ちか", "chika", ["t-row", "k-row", "variant-chi"]],
  ["mixed", "word", "春夏秋冬", "きせつ", "きせつ", "kisetsu", ["k-row", "s-row", "t-row", "variant-tsu"]],
  ["treasure", "word", "夏の くだもの", "すいか", "すいか", "suika", ["s-row", "k-row"]],
  ["treasure", "word", "三時の おたのしみ", "おかし", "おかし", "okashi", ["k-row", "s-row", "variant-shi"]],
  ["treasure", "word", "どんどん ひびく", "たいこ", "たいこ", "taiko", ["t-row", "k-row"]],
  ["treasure", "word", "甘い ひとさじ", "さとう", "さとう", "satou", ["s-row", "t-row"]],
]);

const SH04 = shallowStage("SH04", [
  ["intro", "pattern", "N を つけよう", "なにぬねの", "なにぬねの", "naninuneno", ["n-row"]],
  ["intro", "pattern", "H を つけよう", "はひふへほ", "はひふへほ", "hahifuheho", ["h-row", "variant-fu"]],
  ["intro", "pattern", "M を つけよう", "まみむめも", "まみむめも", "mamimumemo", ["m-row"]],
  ["intro", "pattern", "FU で「ふ」", "ふ", "ふ", "fu", ["h-row", "variant-fu"]],
  ["practice", "pattern", "N の 音を まぜる", "なぬの", "なぬの", "nanuno", ["n-row"]],
  ["practice", "pattern", "H の 音を まぜる", "はふほ", "はふほ", "hafuho", ["h-row", "variant-fu"]],
  ["practice", "word", "花が ひらく", "はな", "はな", "hana", ["h-row", "n-row"]],
  ["practice", "word", "海を すすむ", "ふね", "ふね", "fune", ["h-row", "n-row", "variant-fu"]],
  ["practice", "word", "夜に きらり", "ほし", "ほし", "hoshi", ["h-row", "s-row", "variant-shi"]],
  ["practice", "word", "空の のりもの", "ひこうき", "ひこうき", "hikouki", ["h-row", "k-row"]],
  ["practice", "word", "ひなたで ごろり", "ねこ", "ねこ", "neko", ["n-row", "k-row"]],
  ["practice", "word", "しっぽを ふる", "いぬ", "いぬ", "inu", ["n-row"]],
  ["practice", "word", "やわらかい 生地", "ぬの", "ぬの", "nuno", ["n-row"]],
  ["practice", "word", "海の やわらかい なかま", "なまこ", "なまこ", "namako", ["n-row", "m-row", "k-row"]],
  ["mixed", "word", "小さな たね", "まめ", "まめ", "mame", ["m-row"]],
  ["mixed", "word", "音を きく", "みみ", "みみ", "mimi", ["m-row"]],
  ["mixed", "word", "葉の うらに いる", "むし", "むし", "mushi", ["m-row", "s-row", "variant-shi"]],
  ["mixed", "word", "空から ぽつり", "あめ", "あめ", "ame", ["m-row"]],
  ["mixed", "word", "甘い くだもの", "もも", "もも", "momo", ["m-row"]],
  ["mixed", "word", "青い 水", "うみ", "うみ", "umi", ["m-row"]],
  ["treasure", "word", "宝を しまう", "はこ", "はこ", "hako", ["h-row", "k-row"]],
  ["treasure", "word", "森の ぼうし", "きのこ", "きのこ", "kinoko", ["k-row", "n-row"]],
  ["treasure", "word", "紙を ちょきちょき", "はさみ", "はさみ", "hasami", ["h-row", "s-row", "m-row"]],
  ["treasure", "word", "お日さまの ばしょ", "ひなた", "ひなた", "hinata", ["h-row", "n-row", "t-row"]],
]);

const SH05 = shallowStage("SH05", [
  ["intro", "pattern", "Y を つけよう", "やゆよ", "やゆよ", "yayuyo", ["y-row"]],
  ["intro", "pattern", "R を つけよう", "らりるれろ", "らりるれろ", "rarirurero", ["r-row"]],
  ["intro", "pattern", "W の 音", "わを", "わを", "wawo", ["w-row", "variant-wo"]],
  ["intro", "pattern", "WO で「を」", "を", "を", "wo", ["w-row", "variant-wo"]],
  ["practice", "pattern", "Y の 音を まぜる", "やよ", "やよ", "yayo", ["y-row"]],
  ["practice", "pattern", "R の 音を まぜる", "らるろ", "らるろ", "raruro", ["r-row"]],
  ["practice", "pattern", "W と WO の なみ", "わをわ", "わをわ", "wawowa", ["w-row", "variant-wo"]],
  ["practice", "word", "高い ところ", "やま", "やま", "yama", ["y-row", "m-row"]],
  ["practice", "word", "ねむると 見える", "ゆめ", "ゆめ", "yume", ["y-row", "m-row"]],
  ["practice", "word", "星が 見える 時間", "よる", "よる", "yoru", ["y-row", "r-row"]],
  ["practice", "word", "木の 上を はしる", "りす", "りす", "risu", ["r-row", "s-row"]],
  ["practice", "word", "だれも いない", "るす", "るす", "rusu", ["r-row", "s-row"]],
  ["practice", "word", "むかしの お話", "れきし", "れきし", "rekishi", ["r-row", "k-row", "s-row", "variant-shi"]],
  ["practice", "word", "学校の ながい 道", "ろうか", "ろうか", "rouka", ["r-row", "k-row"]],
  ["mixed", "word", "水辺の いきもの", "わに", "わに", "wani", ["w-row", "n-row"]],
  ["mixed", "word", "花の ある ところ", "にわ", "にわ", "niwa", ["n-row", "w-row"]],
  ["mixed", "word", "水が ながれる", "かわ", "かわ", "kawa", ["k-row", "w-row"]],
  ["mixed", "word", "雪の ような 色", "しろ", "しろ", "shiro", ["s-row", "r-row", "variant-shi"]],
  ["mixed", "word", "雲が うかぶ", "そら", "そら", "sora", ["s-row", "r-row"]],
  ["mixed", "word", "木が いっぱい", "もり", "もり", "mori", ["m-row", "r-row"]],
  ["treasure", "word", "道を はしる", "くるま", "くるま", "kuruma", ["k-row", "r-row", "m-row"]],
  ["treasure", "word", "田んぼの そば", "わら", "わら", "wara", ["w-row", "r-row"]],
  ["treasure", "word", "朝が はじまる", "よあけ", "よあけ", "yoake", ["y-row", "k-row"]],
  ["treasure", "word", "お日さまが 高い", "ひる", "ひる", "hiru", ["h-row", "r-row"]],
]);

const SH06 = shallowStage("SH06", [
  ["intro", "pattern", "G を つけよう", "がぎぐげご", "がぎぐげご", "gagigugego", ["voiced", "g-row"]],
  ["intro", "pattern", "Z と J の 音", "ざじずぜぞ", "ざじずぜぞ", "zajizuzezo", ["voiced", "z-row", "variant-ji"]],
  ["intro", "pattern", "D を つけよう", "だぢづでど", "だぢづでど", "dadidudedo", ["voiced", "d-row", "di-du"]],
  ["intro", "pattern", "B を つけよう", "ばびぶべぼ", "ばびぶべぼ", "babibubebo", ["voiced", "b-row"]],
  ["practice", "pattern", "P を つけよう", "ぱぴぷぺぽ", "ぱぴぷぺぽ", "papipupepo", ["semi-voiced", "p-row"]],
  ["practice", "pattern", "JI で「じ」", "じ", "じ", "ji", ["voiced", "z-row", "variant-ji"]],
  ["practice", "pattern", "DI で「ぢ」", "ぢ", "ぢ", "di", ["voiced", "d-row", "di-du"]],
  ["practice", "pattern", "DU で「づ」", "づ", "づ", "du", ["voiced", "d-row", "di-du"]],
  ["practice", "pattern", "にごる 音を つなぐ", "がざだばぱ", "がざだばぱ", "gazadabapa", ["voiced", "semi-voiced", "g-row", "z-row", "d-row", "b-row", "p-row"]],
  ["practice", "pattern", "O の 音を つなぐ", "ごぞどぼぽ", "ごぞどぼぽ", "gozodobopo", ["voiced", "semi-voiced", "g-row", "z-row", "d-row", "b-row", "p-row"]],
  ["practice", "word", "ドアを あける", "かぎ", "かぎ", "kagi", ["voiced", "g-row"]],
  ["practice", "word", "ものを 入れる", "かご", "かご", "kago", ["voiced", "g-row"]],
  ["practice", "word", "小さな つぶ", "ごま", "ごま", "goma", ["voiced", "g-row", "m-row"]],
  ["practice", "word", "光が はいる", "まど", "まど", "mado", ["voiced", "d-row", "m-row"]],
  ["practice", "word", "元気な こえ", "ぶた", "ぶた", "buta", ["voiced", "b-row", "t-row"]],
  ["practice", "word", "とげの ある 花", "ばら", "ばら", "bara", ["voiced", "b-row", "r-row"]],
  ["practice", "word", "星が ひかる", "ぴかぴか", "ぴかぴか", "pikapika", ["semi-voiced", "p-row", "k-row"]],
  ["practice", "word", "小さな 足音", "ぱたぱた", "ぱたぱた", "patapata", ["semi-voiced", "p-row", "t-row"]],
  ["practice", "word", "大きな みみ", "ぞう", "ぞう", "zou", ["voiced", "z-row"]],
  ["practice", "word", "川を ながれる", "みず", "みず", "mizu", ["voiced", "z-row", "m-row"]],
  ["mixed", "word", "道を たしかめる", "ちず", "ちず", "chizu", ["voiced", "z-row", "t-row", "variant-chi"]],
  ["mixed", "word", "葉を ゆらす", "かぜ", "かぜ", "kaze", ["voiced", "z-row", "k-row"]],
  ["mixed", "word", "足の まんなか", "ひざ", "ひざ", "hiza", ["voiced", "z-row", "h-row"]],
  ["mixed", "word", "畑の まめ", "だいず", "だいず", "daizu", ["voiced", "d-row", "z-row"]],
  ["mixed", "word", "雨の あとの 土", "どろ", "どろ", "doro", ["voiced", "d-row", "r-row"]],
  ["mixed", "word", "黄色い くだもの", "びわ", "びわ", "biwa", ["voiced", "b-row", "w-row"]],
  ["treasure", "word", "おなかが すいた", "ぺこぺこ", "ぺこぺこ", "pekopeko", ["semi-voiced", "p-row", "k-row"]],
  ["treasure", "word", "春の 日ざし", "ぽかぽか", "ぽかぽか", "pokapoka", ["semi-voiced", "p-row", "k-row"]],
  ["treasure", "word", "昔の はきもの", "げた", "げた", "geta", ["voiced", "g-row", "t-row"]],
  ["treasure", "word", "森の 大きな なかま", "ごりら", "ごりら", "gorira", ["voiced", "g-row", "r-row"]],
]);

const SH07 = shallowStage("SH07", [
  ["intro", "pattern", "語尾の「ん」", "ん", "ん", "nn", ["hatsuon", "n-final"]],
  ["intro", "pattern", "A の あとの「ん」", "あん", "あん", "ann", ["hatsuon", "n-final"]],
  ["intro", "pattern", "I の あとの「ん」", "いん", "いん", "inn", ["hatsuon", "n-final"]],
  ["intro", "pattern", "U の あとの「ん」", "うん", "うん", "unn", ["hatsuon", "n-final"]],
  ["practice", "pattern", "E の あとの「ん」", "えん", "えん", "enn", ["hatsuon", "n-final"]],
  ["practice", "pattern", "O の あとの「ん」", "おん", "おん", "onn", ["hatsuon", "n-final"]],
  ["practice", "word", "ページを めくる", "ほん", "ほん", "honn", ["hatsuon", "n-final"]],
  ["practice", "word", "朝の おでかけ", "さんぽ", "さんぽ", "sanpo", ["hatsuon", "n-before-consonant"]],
  ["practice", "word", "文字を かく", "えんぴつ", "えんぴつ", "enpitsu", ["hatsuon", "n-before-consonant"]],
  ["practice", "word", "本を うる 店", "ほんや", "ほんや", "honnya", ["hatsuon", "n-before-y"]],
  ["practice", "word", "店で はたらく 人", "てんいん", "てんいん", "tenninn", ["hatsuon", "n-before-vowel", "n-final"]],
  ["practice", "word", "ニュースを よむ", "しんぶん", "しんぶん", "shinbunn", ["hatsuon", "n-before-consonant", "n-final", "variant-shi"]],
  ["practice", "word", "ふわふわの 食べもの", "ぱん", "ぱん", "pann", ["hatsuon", "n-final"]],
  ["practice", "word", "冬の くだもの", "みかん", "みかん", "mikann", ["hatsuon", "n-final"]],
  ["mixed", "word", "遠くの 人と はなす", "でんわ", "でんわ", "denwa", ["hatsuon", "n-before-consonant"]],
  ["mixed", "word", "長く しまえる 食べもの", "かんづめ", "かんづめ", "kandume", ["hatsuon", "n-before-consonant", "d-row", "di-du"]],
  ["mixed", "word", "今日の 夜", "こんや", "こんや", "konnya", ["hatsuon", "n-before-y"]],
  ["mixed", "word", "空を とぶ むし", "とんぼ", "とんぼ", "tonbo", ["hatsuon", "n-before-consonant"]],
  ["mixed", "word", "力が わいてくる", "げんき", "げんき", "genki", ["hatsuon", "n-before-consonant"]],
  ["mixed", "word", "学校で おしえる 人", "せんせい", "せんせい", "sensei", ["hatsuon", "n-before-consonant"]],
  ["treasure", "word", "赤い やさい", "にんじん", "にんじん", "ninjinn", ["hatsuon", "n-before-consonant", "n-final", "variant-ji"]],
  ["treasure", "word", "甘ずっぱい 実", "あんず", "あんず", "anzu", ["hatsuon", "n-before-consonant"]],
  ["treasure", "word", "歌や がっきの 音", "おんがく", "おんがく", "ongaku", ["hatsuon", "n-before-consonant"]],
  ["treasure", "word", "体を うごかす", "うんどう", "うんどう", "undou", ["hatsuon", "n-before-consonant"]],
]);

const SH08 = shallowStage("SH08", [
  ["intro", "pattern", "K を かさねる", "っか", "っか", "kka", ["sokuon", "double-k"]],
  ["intro", "pattern", "S を かさねる", "っさ", "っさ", "ssa", ["sokuon", "double-s"]],
  ["intro", "pattern", "T を かさねる", "った", "った", "tta", ["sokuon", "double-t"]],
  ["intro", "pattern", "P を かさねる", "っぱ", "っぱ", "ppa", ["sokuon", "double-p"]],
  ["practice", "pattern", "K を もう一度", "っき", "っき", "kki", ["sokuon", "double-k"]],
  ["practice", "word", "手紙に はる", "きって", "きって", "kitte", ["sokuon", "double-t"]],
  ["practice", "word", "木の ねもと", "ねっこ", "ねっこ", "nekko", ["sokuon", "double-k"]],
  ["practice", "word", "音を ひびかせる", "らっぱ", "らっぱ", "rappa", ["sokuon", "double-p"]],
  ["practice", "word", "読むものが いっぱい", "ざっし", "ざっし", "zasshi", ["sokuon", "double-s", "variant-shi"]],
  ["practice", "word", "今日の できごと", "にっき", "にっき", "nikki", ["sokuon", "double-k"]],
  ["practice", "word", "みんなで 学ぶ", "がっこう", "がっこう", "gakkou", ["sokuon", "double-k"]],
  ["practice", "word", "電車に のる しるし", "きっぷ", "きっぷ", "kippu", ["sokuon", "double-p"]],
  ["practice", "word", "水を 入れる", "こっぷ", "こっぷ", "koppu", ["sokuon", "double-p"]],
  ["practice", "word", "かならず そうなる", "きっと", "きっと", "kitto", ["sokuon", "double-t"]],
  ["practice", "word", "もう 少し", "もっと", "もっと", "motto", ["sokuon", "double-t"]],
  ["mixed", "word", "ついに ついた", "やっと", "やっと", "yatto", ["sokuon", "double-t"]],
  ["mixed", "word", "はじめから おわりまで", "ずっと", "ずっと", "zutto", ["sokuon", "double-t"]],
  ["mixed", "word", "お話を かく 人", "さっか", "さっか", "sakka", ["sokuon", "double-k"]],
  ["mixed", "word", "しらべた 答え", "けっか", "けっか", "kekka", ["sokuon", "double-k"]],
  ["mixed", "word", "手を きれいに", "せっけん", "せっけん", "sekkenn", ["sokuon", "double-k", "hatsuon", "n-final"]],
  ["treasure", "word", "前を むいて", "まっすぐ", "まっすぐ", "massugu", ["sokuon", "double-s"]],
  ["treasure", "word", "木の みどり", "はっぱ", "はっぱ", "happa", ["sokuon", "double-p"]],
  ["treasure", "word", "音を 立てずに", "こっそり", "こっそり", "kossori", ["sokuon", "double-s"]],
  ["treasure", "word", "えがおに なる", "にっこり", "にっこり", "nikkori", ["sokuon", "double-k"]],
]);

const SH09 = shallowStage("SH09", [
  ["intro", "word", "お祝いの おかし", "ケーキ", "けーき", "ke-ki", ["choon"]],
  ["intro", "word", "あたたかい ひと皿", "スープ", "すーぷ", "su-pu", ["choon"]],
  ["intro", "word", "文字を のこす", "ノート", "のーと", "no-to", ["choon"]],
  ["intro", "word", "ころころ はずむ", "ボール", "ぼーる", "bo-ru", ["choon"]],
  ["practice", "word", "外に きていく", "コート", "こーと", "ko-to", ["choon"]],
  ["practice", "word", "紙を とめる", "テープ", "てーぷ", "te-pu", ["choon"]],
  ["practice", "word", "みんなで あそぶ", "ゲーム", "げーむ", "ge-mu", ["choon"]],
  ["practice", "word", "冬に あたたかい", "セーター", "せーたー", "se-ta-", ["choon"]],
  ["practice", "word", "香りを たのしむ", "コーヒー", "こーひー", "ko-hi-", ["choon"]],
  ["practice", "word", "船を つなぐ", "ロープ", "ろーぷ", "ro-pu", ["choon"]],
  ["practice", "word", "水で およぐ", "プール", "ぷーる", "pu-ru", ["choon"]],
  ["practice", "word", "公園の あそび道具", "シーソー", "しーそー", "shi-so-", ["choon", "variant-shi"]],
  ["practice", "word", "水の 上を すすむ", "ボート", "ぼーと", "bo-to", ["choon"]],
  ["practice", "word", "料理に かける", "ソース", "そーす", "so-su", ["choon"]],
  ["mixed", "word", "まどに かける", "カーテン", "かーてん", "ka-tenn", ["choon", "hatsuon", "n-final"]],
  ["mixed", "word", "ごはんに かける", "カレー", "かれー", "kare-", ["choon"]],
  ["mixed", "word", "長さを はかる", "メートル", "めーとる", "me-toru", ["choon"]],
  ["mixed", "word", "めざす ばしょ", "ゴール", "ごーる", "go-ru", ["choon"]],
  ["mixed", "word", "物語の 主人公", "ヒーロー", "ひーろー", "hi-ro-", ["choon"]],
  ["mixed", "word", "しらべた きろく", "データ", "でーた", "de-ta", ["choon"]],
  ["treasure", "word", "力を あわせる", "チーム", "ちーむ", "chi-mu", ["choon", "variant-chi"]],
  ["treasure", "word", "ぺたりと はる", "シール", "しーる", "shi-ru", ["choon", "variant-shi"]],
  ["treasure", "word", "ものを 入れる", "ケース", "けーす", "ke-su", ["choon"]],
  ["treasure", "word", "字を 大きく かく", "マーカー", "まーかー", "ma-ka-", ["choon"]],
]);

const SH10 = shallowStage("SH10", [
  ["intro", "pattern", "K と Y の 音", "きゃきゅきょ", "きゃきゅきょ", "kyakyukyo", ["yoon", "k-yoon"]],
  ["intro", "pattern", "SH の 小さな 音", "しゃしゅしょ", "しゃしゅしょ", "shashusho", ["yoon", "s-yoon"]],
  ["intro", "pattern", "CH の 小さな 音", "ちゃちゅちょ", "ちゃちゅちょ", "chachucho", ["yoon", "t-yoon"]],
  ["intro", "pattern", "N と Y の 音", "にゃにゅにょ", "にゃにゅにょ", "nyanyunyo", ["yoon", "n-yoon"]],
  ["practice", "pattern", "H と Y の 音", "ひゃひゅひょ", "ひゃひゅひょ", "hyahyuhyo", ["yoon", "h-yoon"]],
  ["practice", "pattern", "M と Y の 音", "みゃみゅみょ", "みゃみゅみょ", "myamyumyo", ["yoon", "m-yoon"]],
  ["practice", "pattern", "R と Y の 音", "りゃりゅりょ", "りゃりゅりょ", "ryaryuryo", ["yoon", "r-yoon"]],
  ["practice", "word", "お店に 来た 人", "きゃく", "きゃく", "kyaku", ["yoon", "k-yoon"]],
  ["practice", "word", "みどりの やさい", "きゅうり", "きゅうり", "kyuuri", ["yoon", "k-yoon"]],
  ["practice", "word", "音楽の 一つ", "きょく", "きょく", "kyoku", ["yoon", "k-yoon"]],
  ["practice", "word", "思い出を のこす", "しゃしん", "しゃしん", "shashinn", ["yoon", "s-yoon", "hatsuon", "n-final"]],
  ["practice", "word", "好きな こと", "しゅみ", "しゅみ", "shumi", ["yoon", "s-yoon"]],
  ["practice", "word", "楽しい ごはん", "しょくじ", "しょくじ", "shokuji", ["yoon", "s-yoon", "variant-ji"]],
  ["practice", "word", "ごはんの うつわ", "ちゃわん", "ちゃわん", "chawann", ["yoon", "t-yoon", "hatsuon", "n-final"]],
  ["practice", "word", "よく 見て すすむ", "ちゅうい", "ちゅうい", "chuui", ["yoon", "t-yoon"]],
  ["practice", "word", "お金を ためる", "ちょきん", "ちょきん", "chokinn", ["yoon", "t-yoon", "hatsuon", "n-final"]],
  ["practice", "word", "ねこの こえ", "にゃんこ", "にゃんこ", "nyanko", ["yoon", "n-yoon", "hatsuon", "n-before-consonant"]],
  ["practice", "word", "学校に はいる", "にゅうがく", "にゅうがく", "nyuugaku", ["yoon", "n-yoon"]],
  ["practice", "word", "芽が のびる 音", "にょきにょき", "にょきにょき", "nyokinyoki", ["yoon", "n-yoon"]],
  ["practice", "word", "百まで かぞえる", "ひゃく", "ひゃく", "hyaku", ["yoon", "h-yoon"]],
  ["practice", "word", "風が ふく 音", "ひゅうひゅう", "ひゅうひゅう", "hyuuhyuu", ["yoon", "h-yoon"]],
  ["mixed", "word", "数を あらわす 表", "ひょう", "ひょう", "hyou", ["yoon", "h-yoon"]],
  ["mixed", "word", "手首で かんじる", "みゃく", "みゃく", "myaku", ["yoon", "m-yoon"]],
  ["mixed", "word", "名前の もう一つ", "みょうじ", "みょうじ", "myouji", ["yoon", "m-yoon", "variant-ji"]],
  ["mixed", "word", "空を とぶ 生きもの", "りゅう", "りゅう", "ryuu", ["yoon", "r-yoon"]],
  ["mixed", "word", "遠くへ でかける", "りょこう", "りょこう", "ryokou", ["yoon", "r-yoon"]],
  ["treasure", "word", "大むかしの 生きもの", "きょうりゅう", "きょうりゅう", "kyouryuu", ["yoon", "k-yoon", "r-yoon"]],
  ["treasure", "word", "家で とりくむ", "しゅくだい", "しゅくだい", "shukudai", ["yoon", "s-yoon"]],
  ["treasure", "word", "料理の いい 香り", "しょうゆ", "しょうゆ", "shouyu", ["yoon", "s-yoon"]],
  ["treasure", "word", "花の まわりを とぶ", "ちょうちょ", "ちょうちょ", "choucho", ["yoon", "t-yoon"]],
]);

const SH11 = shallowStage("SH11", [
  ["intro", "pattern", "G と Y の 音", "ぎゃぎゅぎょ", "ぎゃぎゅぎょ", "gyagyugyo", ["yoon", "voiced", "g-yoon"]],
  ["intro", "pattern", "J の 小さな 音", "じゃじゅじょ", "じゃじゅじょ", "jajujo", ["yoon", "voiced", "j-yoon"]],
  ["intro", "pattern", "D と Y の 音", "ぢゃぢゅぢょ", "ぢゃぢゅぢょ", "dyadyudyo", ["yoon", "voiced", "d-yoon"]],
  ["intro", "pattern", "B と Y の 音", "びゃびゅびょ", "びゃびゅびょ", "byabyubyo", ["yoon", "voiced", "b-yoon"]],
  ["practice", "pattern", "P と Y の 音", "ぴゃぴゅぴょ", "ぴゃぴゅぴょ", "pyapyupyo", ["yoon", "semi-voiced", "p-yoon"]],
  ["practice", "word", "反対の むき", "ぎゃく", "ぎゃく", "gyaku", ["yoon", "voiced", "g-yoon"]],
  ["practice", "word", "白い のみもの", "ぎゅうにゅう", "ぎゅうにゅう", "gyuunyuu", ["yoon", "voiced", "g-yoon", "n-yoon"]],
  ["practice", "word", "学校の できごと", "ぎょうじ", "ぎょうじ", "gyouji", ["yoon", "voiced", "g-yoon", "variant-ji"]],
  ["practice", "word", "学校を 旅立つ", "そつぎょう", "そつぎょう", "sotsugyou", ["yoon", "voiced", "g-yoon", "variant-tsu"]],
  ["practice", "word", "水が 出る ところ", "じゃぐち", "じゃぐち", "jaguchi", ["yoon", "voiced", "j-yoon"]],
  ["practice", "word", "手を 出して あそぶ", "じゃんけん", "じゃんけん", "jankenn", ["yoon", "voiced", "j-yoon", "hatsuon", "n-before-consonant", "n-final"]],
  ["practice", "word", "道を ふさぐ", "じゃま", "じゃま", "jama", ["yoon", "voiced", "j-yoon"]],
  ["practice", "word", "小さな 石", "じゃり", "じゃり", "jari", ["yoon", "voiced", "j-yoon"]],
  ["practice", "word", "元気に とびこす", "ジャンプ", "じゃんぷ", "janpu", ["yoon", "voiced", "j-yoon", "hatsuon", "n-before-consonant"]],
  ["practice", "word", "出かける したく", "じゅんび", "じゅんび", "junbi", ["yoon", "voiced", "j-yoon", "hatsuon", "n-before-consonant"]],
  ["practice", "word", "教室で 学ぶ", "じゅぎょう", "じゅぎょう", "jugyou", ["yoon", "voiced", "j-yoon", "g-yoon"]],
  ["practice", "word", "冷たい のみもの", "ジュース", "じゅーす", "ju-su", ["yoon", "voiced", "j-yoon", "choon"]],
  ["practice", "word", "まほうの ことば", "じゅもん", "じゅもん", "jumonn", ["yoon", "voiced", "j-yoon", "hatsuon", "n-final"]],
  ["practice", "word", "白い 服で れんしゅう", "じゅうどう", "じゅうどう", "juudou", ["yoon", "voiced", "j-yoon"]],
  ["mixed", "word", "花に 水を あげる", "じょうろ", "じょうろ", "jouro", ["yoon", "voiced", "j-yoon"]],
  ["mixed", "word", "うまく できる", "じょうず", "じょうず", "jouzu", ["yoon", "voiced", "j-yoon"]],
  ["mixed", "word", "ゆっくり はしる", "じょぎんぐ", "じょぎんぐ", "jogingu", ["yoon", "voiced", "j-yoon", "hatsuon", "n-before-consonant"]],
  ["mixed", "word", "百が 三つ", "さんびゃく", "さんびゃく", "sanbyaku", ["yoon", "voiced", "b-yoon", "hatsuon", "n-before-consonant"]],
  ["mixed", "word", "百が 六つ", "ろっぴゃく", "ろっぴゃく", "roppyaku", ["yoon", "semi-voiced", "p-yoon", "sokuon", "double-p"]],
  ["mixed", "word", "強い 風の 音", "びゅうびゅう", "びゅうびゅう", "byuubyuu", ["yoon", "voiced", "b-yoon"]],
  ["mixed", "word", "お医者さんが いる", "びょういん", "びょういん", "byouinn", ["yoon", "voiced", "b-yoon", "hatsuon", "n-final"]],
  ["treasure", "word", "元気に なおそう", "びょうき", "びょうき", "byouki", ["yoon", "voiced", "b-yoon"]],
  ["treasure", "word", "病院の へや", "びょうしつ", "びょうしつ", "byoushitsu", ["yoon", "voiced", "b-yoon", "variant-shi", "variant-tsu"]],
  ["treasure", "word", "笛の ような 風", "ぴゅうぴゅう", "ぴゅうぴゅう", "pyuupyuu", ["yoon", "semi-voiced", "p-yoon"]],
  ["treasure", "word", "うさぎが とぶ 音", "ぴょん", "ぴょん", "pyonn", ["yoon", "semi-voiced", "p-yoon", "hatsuon", "n-final"]],
]);

export const SHALLOW_PROBLEM_CONTENT = [
  ...SH01,
  ...SH02,
  ...SH03,
  ...SH04,
  ...SH05,
  ...SH06,
  ...SH07,
  ...SH08,
  ...SH09,
  ...SH10,
  ...SH11,
];
