export const STAGE_CONTENT = [
  { id: "S00", name: "潮だまりのぽっち", description: "F と J のぽっちに、指をかえそう。", introducedKeys: ["f", "j"], availableKeys: ["f", "j"], minCompletedPlays: 1, minAccuracy: 0.8, medalCriteria: { carefulMinAccuracy: 0.95, speedMaxMsPerKey: 1300 } },
  { id: "S01", name: "左手の浅瀬", description: "左手のおうちを、ゆっくりたどろう。", introducedKeys: ["a", "s", "d"], availableKeys: ["a", "s", "d", "f"], minCompletedPlays: 2, minAccuracy: 0.8, medalCriteria: { carefulMinAccuracy: 0.95, speedMaxMsPerKey: 1200 } },
  { id: "S02", name: "右手の浅瀬", description: "右手も、おうちに帰ってこられるかな。", introducedKeys: ["k", "l"], availableKeys: ["j", "k", "l"], minCompletedPlays: 2, minAccuracy: 0.8, medalCriteria: { carefulMinAccuracy: 0.95, speedMaxMsPerKey: 1200 } },
  { id: "S03", name: "ホームポジションの海", description: "左右の手で、小さな波をつなごう。", introducedKeys: ["a", "s", "d", "f", "j", "k", "l"], availableKeys: ["a", "s", "d", "f", "j", "k", "l"], minCompletedPlays: 3, minAccuracy: 0.82, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1100 } },
  { id: "S04", name: "左手の珊瑚礁", description: "左手をのばして、上の波をたどろう。", introducedKeys: ["q", "w", "e", "r", "t"], availableKeys: ["a", "s", "d", "f", "q", "w", "e", "r", "t"], minCompletedPlays: 2, minAccuracy: 0.82, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1100 } },
  { id: "S05", name: "右手の珊瑚礁", description: "右手をのばして、上の波をたどろう。", introducedKeys: ["y", "u", "i", "o", "p"], availableKeys: ["j", "k", "l", "y", "u", "i", "o", "p"], minCompletedPlays: 2, minAccuracy: 0.82, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1100 } },
  { id: "S06", name: "両手の珊瑚礁", description: "上の段を、両手でつないでみよう。", introducedKeys: [], availableKeys: ["a", "s", "d", "f", "j", "k", "l", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p"], minCompletedPlays: 3, minAccuracy: 0.85, medalCriteria: { carefulMinAccuracy: 0.97, speedMaxMsPerKey: 1000 } },
  { id: "S07", name: "左手の海草原", description: "左手で、下の段へもぐってみよう。", introducedKeys: ["z", "x", "c", "v", "b"], availableKeys: ["a", "s", "d", "f", "q", "w", "e", "r", "t", "z", "x", "c", "v", "b"], minCompletedPlays: 2, minAccuracy: 0.85, medalCriteria: { carefulMinAccuracy: 0.97, speedMaxMsPerKey: 1000 } },
  { id: "S08", name: "右手の海草原", description: "右手で、下の段へもぐってみよう。", introducedKeys: ["n", "m", ",", ".", "/"], availableKeys: ["j", "k", "l", "y", "u", "i", "o", "p", "n", "m", ",", ".", "/"], minCompletedPlays: 2, minAccuracy: 0.85, medalCriteria: { carefulMinAccuracy: 0.97, speedMaxMsPerKey: 1000 } },
  { id: "S09", name: "ことばの深み", description: "ひらがなのことばを、ローマ字で打とう。", introducedKeys: [], availableKeys: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"], minCompletedPlays: 3, minAccuracy: 0.87, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1300 } },
];
