export const STAGE_CONTENT = [
  { id: "S00", regionId: "tidepool", name: "潮だまりのぽっち", description: "F と J のぽっちに、指をかえそう。", introducedKeys: ["f", "j"], availableKeys: ["f", "j"], minCompletedPlays: 1, minAccuracy: 0.8, medalCriteria: { carefulMinAccuracy: 0.95, speedMaxMsPerKey: 1300 } },
  { id: "S01", regionId: "tidepool", name: "潮だまりの左手", description: "左手のおうちを、ゆっくりたどろう。", introducedKeys: ["a", "s", "d"], availableKeys: ["a", "s", "d", "f"], minCompletedPlays: 2, minAccuracy: 0.8, medalCriteria: { carefulMinAccuracy: 0.95, speedMaxMsPerKey: 1200 } },
  { id: "S02", regionId: "tidepool", name: "潮だまりの右手", description: "右手も、おうちに帰ってこられるかな。", introducedKeys: ["k", "l"], availableKeys: ["j", "k", "l"], minCompletedPlays: 2, minAccuracy: 0.8, medalCriteria: { carefulMinAccuracy: 0.95, speedMaxMsPerKey: 1200 } },
  { id: "S03", regionId: "tidepool", name: "潮だまりのリズム", description: "左右の手で、小さな波をつなごう。", introducedKeys: ["a", "s", "d", "f", "j", "k", "l"], availableKeys: ["a", "s", "d", "f", "j", "k", "l"], minCompletedPlays: 3, minAccuracy: 0.82, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1100 } },
  { id: "S04", regionId: "tidepool", name: "潮だまりの上の波", description: "左手をのばして、上の波をたどろう。", introducedKeys: ["q", "w", "e", "r", "t"], availableKeys: ["a", "s", "d", "f", "q", "w", "e", "r", "t"], minCompletedPlays: 2, minAccuracy: 0.82, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1100 } },
  { id: "S05", regionId: "tidepool", name: "潮だまりの右の波", description: "右手をのばして、上の波をたどろう。", introducedKeys: ["y", "u", "i", "o", "p"], availableKeys: ["j", "k", "l", "y", "u", "i", "o", "p"], minCompletedPlays: 2, minAccuracy: 0.82, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1100 } },
  { id: "S06", regionId: "tidepool", name: "潮だまりの大きな波", description: "上の段を、両手でつないでみよう。", introducedKeys: [], availableKeys: ["a", "s", "d", "f", "j", "k", "l", "q", "w", "e", "r", "t", "y", "u", "i", "o", "p"], minCompletedPlays: 3, minAccuracy: 0.85, medalCriteria: { carefulMinAccuracy: 0.97, speedMaxMsPerKey: 1000 } },
  { id: "S07", regionId: "tidepool", name: "潮だまりの左の砂", description: "左手で、下の段へもぐってみよう。", introducedKeys: ["z", "x", "c", "v", "b"], availableKeys: ["a", "s", "d", "f", "q", "w", "e", "r", "t", "z", "x", "c", "v", "b"], minCompletedPlays: 2, minAccuracy: 0.85, medalCriteria: { carefulMinAccuracy: 0.97, speedMaxMsPerKey: 1000 } },
  { id: "S08", regionId: "tidepool", name: "潮だまりの右の砂", description: "右手で、下の段へもぐってみよう。", introducedKeys: ["n", "m", ",", ".", "/"], availableKeys: ["j", "k", "l", "y", "u", "i", "o", "p", "n", "m", ",", ".", "/"], minCompletedPlays: 2, minAccuracy: 0.85, medalCriteria: { carefulMinAccuracy: 0.97, speedMaxMsPerKey: 1000 } },
  { id: "S09", regionId: "tidepool", name: "潮だまりのことば", description: "ひらがなのことばを、ローマ字で打とう。", introducedKeys: [], availableKeys: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z"], minCompletedPlays: 3, minAccuracy: 0.87, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1300 } },
  { id: "S10", regionId: "shallows", name: "浅瀬のはずむ波", description: "「ん・っ・ー」の音を、ことばでたどろう。", introducedKeys: ["-"], availableKeys: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "-"], focusTags: ["hatsuon", "sokuon", "choon"], minCompletedPlays: 3, minAccuracy: 0.87, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1350 } },
  { id: "S11", regionId: "shallows", name: "浅瀬の小さな波", description: "小さい「ゃ・ゅ・ょ」が入ることばを打とう。", introducedKeys: [], availableKeys: ["a", "b", "c", "d", "e", "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p", "q", "r", "s", "t", "u", "v", "w", "x", "y", "z", "-"], focusTags: ["yoon"], minCompletedPlays: 4, minAccuracy: 0.87, medalCriteria: { carefulMinAccuracy: 0.96, speedMaxMsPerKey: 1400 } },
];
